const translations = {
    'Knight': 'Caballero',
    'Archers': 'Arqueras',
    'Goblins': 'Duendes',
    'Giant': 'Gigante',
    'P.E.K.K.A': 'P.E.K.K.A',
    'Minions': 'Esbirros',
    'Balloon': 'Globo bombástico',
    'Witch': 'Bruja',
    'Barbarians': 'Bárbaros',
    'Golem': 'Golem',
    'Skeletons': 'Esqueletos',
    'Valkyrie': 'Valquiria',
    'Skeleton Army': 'Ejército de esqueletos',
    'Bomber': 'Bombardero',
    'Musketeer': 'Mosquetera',
    'Baby Dragon': 'Bebé Dragón',
    'Prince': 'Príncipe',
    'Wizard': 'Mago',
    'Mini P.E.K.K.A': 'Mini P.E.K.K.A',
    'Spear Goblins': 'Duendes con lanza',
    'Giant Skeleton': 'Esqueleto gigante',
    'Hog Rider': 'Montapuertos',
    'Minion Horde': 'Horda de esbirros',
    'Ice Wizard': 'Mago de hielo',
    'Royal Giant': 'Gigante Noble',
    'Guards': 'Guardias',
    'Princess': 'Princesa',
    'Dark Prince': 'Príncipe oscuro',
    'Three Musketeers': 'Trío de Mosqueteras',
    'Lava Hound': 'Sabueso de lava',
    'Ice Spirit': 'Espíritu de hielo',
    'Fire Spirits': 'Espíritus de fuego',
    'Miner': 'Minero',
    'Sparky': 'Chispitas',
    'Bowler': 'Lanzarrocas',
    'Lumberjack': 'Leñador',
    'Battle Ram': 'Ariete de batalla',
    'Inferno Dragon': 'Dragón Infernal',
    'Ice Golem': 'Golem de hielo',
    'Mega Minion': 'Megaesbirro',
    'Dart Goblin': 'Duende lanzadardos',
    'Goblin Gang': 'Pandilla de Duendes',
    'Electro Wizard': 'Mago eléctrico',
    'Elite Barbarians': 'Bárbaros de élite',
    'Hunter': 'Cazador',
    'Executioner': 'Verdugo',
    'Bandit': 'Bandida',
    'Royal Recruits': 'Reclutas Reales',
    'Night Witch': 'Bruja nocturna',
    'Bats': 'Murciélagos',
    'Royal Ghost': 'Fantasma Real',
    'Ram Rider': 'Montacarneros',
    'Zappies': 'Electrocutadores',
    'Rascals': 'Pillos',
    'Cannon Cart': 'Cañón con Ruedas',
    'Mega Knight': 'Megacaballero',
    'Skeleton Barrel': 'Barril de Esqueletos',
    'Flying Machine': 'Máquina Voladora',
    'Wall Breakers': 'Rompemuros',
    'Royal Hogs': 'Cerdos Reales',
    'Goblin Giant': 'Duende Gigante',
    'Fisherman': 'Pescador',
    'Magic Archer': 'Arquero Mágico',
    'Electro Dragon': 'Dragón Eléctrico',
    'Firecracker': 'Lanzafuegos',
    'Elixir Golem': 'Golem de Elixir',
    'Battle Healer': 'Curandera',
    'Skeleton Dragons': 'Dragones Esqueléticos',
    'Mother Witch': 'Bruja Madre',
    'Electro Spirit': 'Espíritu Eléctrico',
    'Electro Giant': 'Gigante Eléctrico',
    'Cannon': 'Cañón',
    'Goblin Hut': 'Choza de Duendes',
    'Mortar': 'Mortero',
    'Inferno Tower': 'Torre Infernal',
    'Bomb Tower': 'Torre bombardera',
    'Barbarian Hut': 'Choza de bárbaros',
    'Tesla': 'Torre Tesla',
    'Elixir Collector': 'Recolector de elixir',
    'X-Bow': 'Ballesta',
    'Tombstone': 'Lápida',
    'Furnace': 'Horno',
    'Goblin Cage': 'Duende Forzudo',
    'Fireball': 'Bola de fuego',
    'Arrows': 'Flechas',
    'Rage': 'Furia',
    'Rocket': 'Cohete',
    'Goblin Barrel': 'Barril de duendes',
    'Freeze': 'Hielo',
    'Mirror': 'Espejo',
    'Lightning': 'Rayo',
    'Zap': 'Descarga',
    'Poison': 'Veneno',
    'Graveyard': 'Cementerio',
    'The Log': 'El Tronco',
    'Tornado': 'Tornado',
    'Clone': 'Clon',
    'Earthquake': 'Terremoto',
    'Barbarian Barrel': 'Barril de Bárbaros',
    'Heal Spirit': 'Espíritu Sanador',
    'Giant Snowball': 'Bola de nieve',
    'Royal Delivery': 'Paquete Real'
};

export default function Translate(id) {
    return translations[id];
}